# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/eldo/work/NTI/Design/Day_ten/fpga/PYNQ-Z2 v1.0.xdc

# Block Designs: bd/soc_lab_2/soc_lab_2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_lab_2 || ORIG_REF_NAME==soc_lab_2} -quiet] -quiet

# IP: bd/soc_lab_2/ip/soc_lab_2_processing_system7_0_0/soc_lab_2_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_lab_2_processing_system7_0_0 || ORIG_REF_NAME==soc_lab_2_processing_system7_0_0} -quiet] -quiet

# XDC: /home/eldo/work/NTI/Design/Day_ten/fpga/soc_lab_2/soc_lab_2/soc_lab_2.gen/sources_1/bd/soc_lab_2/soc_lab_2_ooc.xdc
