set_property SRC_FILE_INFO {cfile:{F:/NTI/Design/Day_ten/fpga/PYNQ-Z2 v1.0.xdc} rfile:{../../../../PYNQ-Z2 v1.0.xdc} id:1} [current_design]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D19   IOSTANDARD LVCMOS33 } [get_ports { button[0]}]; #IO_L4P_T0_35 Sch=btn[0]                 btn[0]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D20   IOSTANDARD LVCMOS33 } [get_ports { button[1] }]; #IO_L4N_T0_35 Sch=btn[1]                 btn[1]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L20   IOSTANDARD LVCMOS33 } [get_ports { button[2] }]; #IO_L9N_T1_DQS_AD3N_35 Sch=btn[2]        btn[2]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L19   IOSTANDARD LVCMOS33 } [get_ports { button[3] }]; #IO_L9P_T1_DQS_AD3P_35 Sch=btn[3]        btn[3]
