// Copyright (C) 2025  Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus Prime License Agreement,
// the Altera IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Altera and sold by Altera or its authorized distributors.  Please
// refer to the Altera Software License Subscription Agreements 
// on the Quartus Prime software download page.

// Generated by Quartus Prime Version 25.1std.0 Build 1129 10/21/2025 SC Lite Edition
// Created on Tue Aug 25 10:03:14 2026

// synthesis message_off 10175

`timescale 1ns/1ns

module FSM (
    reset,clock,a,b,
    y0,y1);

    input reset;
    input clock;
    input a;
    input b;
    tri0 reset;
    tri0 a;
    tri0 b;
    output y0;
    output y1;
    reg y0;
    reg y1;
    reg [2:0] fstate;
    reg [2:0] reg_fstate;
    parameter S0=0,S2=1,S1=2;

    always @(posedge clock or negedge reset)
    begin
        if (~reset) begin
            fstate <= S0;
        end
        else begin
            fstate <= reg_fstate;
        end
    end

    always @(fstate or a or b)
    begin
        y0 <= 1'b0;
        y1 <= 1'b0;
        case (fstate)
            S0: begin
                if (~(a))
                    reg_fstate <= S0;
                else if ((a & ~(b)))
                    reg_fstate <= S1;
                else if ((a & b))
                    reg_fstate <= S2;
                // Inserting 'else' block to prevent latch inference
                else
                    reg_fstate <= S0;

                y1 <= 1'b1;

                if ((a & b))
                    y0 <= 1'b1;
                // Inserting 'else' block to prevent latch inference
                else
                    y0 <= 1'b0;
            end
            S2: begin
                reg_fstate <= S0;
            end
            S1: begin
                if (~(a))
                    reg_fstate <= S1;
                else if (a)
                    reg_fstate <= S0;
                // Inserting 'else' block to prevent latch inference
                else
                    reg_fstate <= S1;

                y1 <= 1'b1;
            end
            default: begin
                y0 <= 1'bx;
                y1 <= 1'bx;
                $display ("Reach undefined state");
            end
        endcase
    end
endmodule // FSM
